In [2]:
import torch

In [2]:
t1 = torch.tensor([1, 1, 1])

In [3]:
t1.unsqueeze(dim=0)

tensor([[1, 1, 1]])

In [4]:
t1.unsqueeze(dim=1)

tensor([[1],
        [1],
        [1]])

In [6]:
print(t1.shape)
print(t1.unsqueeze(dim=0).shape)
print(t1.unsqueeze(dim=1).shape)

torch.Size([3])
torch.Size([1, 3])
torch.Size([3, 1])


In [3]:
t1 = torch.tensor([1, 1, 1])
t2 = torch.tensor([2, 2, 2])
t3 = torch.tensor([3, 3, 3])

In [9]:
torch.cat(
    (t1, t2, t3),
    dim=0
)

tensor([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [16]:
torch.stack(
    (t1, t2, t3),
    dim=0
)

tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]])

In [6]:
torch.cat(
    (
        t1.unsqueeze(0),
        t2.unsqueeze(0),
        t3.unsqueeze(0)
    ),
    dim=0
)

tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]])

In [5]:
torch.cat(
    (
        t1.unsqueeze(1),
        t2.unsqueeze(1),
        t3.unsqueeze(1)
    ),
    dim=1
)

tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]])

In [1]:
import tensorflow as tf 

In [3]:
t1 = tf.constant([1, 1, 1])
t2 = tf.constant([2, 2, 2])
t3 = tf.constant([3, 3, 3])

In [4]:
tf.concat(
    (t1, t2, t3),
    axis=0
)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 1, 1, 2, 2, 2, 3, 3, 3])>

In [5]:
tf.stack(
    (t1, t2, t3),
    axis=0
)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])>

In [7]:
tf.concat(
    (
        tf.expand_dims(t1, 1),
        tf.expand_dims(t2, 1),
        tf.expand_dims(t3, 1)
    ),
    axis=1
)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])>

In [1]:
import numpy as np

In [2]:
t1 = np.array([1, 1, 1])
t2 = np.array([2, 2, 2])
t3 = np.array([3, 3, 3])

In [3]:
np.concatenate(
    (t1, t2, t3),
    axis=0
)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [4]:
np.stack(
    (t1, t2, t3),
    axis=1
)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [5]:
np.concatenate(
    (
        np.expand_dims(t1, 1),
        np.expand_dims(t2, 1),
        np.expand_dims(t3, 1)
    ),
    axis=1
)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])