### **ETL(Extract Transform Load)**

In [1]:
import torch
import torchvision
import torchvision.transforms as transforms

In [2]:
train_set = torchvision.datasets.FashionMNIST(
    root='./data/FashionMNIST'
    ,train=True
    ,download=True
    ,transform=transforms.Compose([
        transforms.ToTensor()
    ])
)


In [3]:
type(train_set)
train_set

Dataset FashionMNIST
    Number of datapoints: 60000
    Root location: ./data/FashionMNIST
    Split: Train
    StandardTransform
Transform: Compose(
               ToTensor()
           )

In [4]:
train_loader = torch.utils.data.DataLoader(
    train_set, batch_size=10
)

In [5]:
import numpy as np
import matplotlib.pyplot as plt

torch.set_printoptions(linewidth=120)

In [6]:
len(train_set)

60000

In [7]:
train_set.train_labels

d:\AConda\lib\site-packages\torchvision\datasets\mnist.py:65: UserWarning: train_labels has been renamed targets
  warnings.warn("train_labels has been renamed targets")


tensor([9, 0, 0,  ..., 3, 0, 5])

In [8]:
train_set.train_labels.bincount()

tensor([6000, 6000, 6000, 6000, 6000, 6000, 6000, 6000, 6000, 6000])

In [9]:
import torch.nn as nn
import torch.nn.functional as F

In [10]:
class Network:
    def __init__(self):
        self.layer = None

    def forward(self, t):
        t = self.layer(t)
        return t

In [11]:
class Network(nn.Module):
    def __init__(self):
        super(Network, self).__init__()
        self.conv1 = nn.Conv2d(in_channels=1, out_channels=6, kernel_size=5)
        self.conv2 = nn.Conv2d(in_channels=6, out_channels=12, kernel_size=5)

        self.fc1 = nn.Linear(in_features=12*4*4, out_features=120)
        self.fc2 = nn.Linear(in_features=120, out_features=60)
        self.out = nn.Linear(in_features=60, out_features=10)

    def forward(self, t):
        t = self.conv1(t)
        t = F.relu(t)
        t = F.max_pool2d(t,  kernel_size=2, stride=1)
        
        t = self.conv2(t)
        t = F.relu(t)
        t = F.max_pool2d(t, kernel_size=2, stride=1)
        
        t = t.reshape(-1, 12 * 4 * 4)
        t = self.fc1(t)
        t = F.relu(t)
        
        t = self.fc2(t)
        t = F.relu(t)
        
        t = self.out(t)
        t = F.softmax(t)
        
        return t
    
    # def __repr__(self):
    #     return "XYY"

In [12]:
network = Network()
network

Network(
  (conv1): Conv2d(1, 6, kernel_size=(5, 5), stride=(1, 1))
  (conv2): Conv2d(6, 12, kernel_size=(5, 5), stride=(1, 1))
  (fc1): Linear(in_features=192, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=60, bias=True)
  (out): Linear(in_features=60, out_features=10, bias=True)
)

In [13]:
network.conv1

Conv2d(1, 6, kernel_size=(5, 5), stride=(1, 1))

In [14]:
network.conv2

Conv2d(6, 12, kernel_size=(5, 5), stride=(1, 1))

In [15]:
network.fc1

Linear(in_features=192, out_features=120, bias=True)

In [16]:
network.fc2

Linear(in_features=120, out_features=60, bias=True)

In [17]:
network.out

Linear(in_features=60, out_features=10, bias=True)

In [18]:
network.conv1.weight.shape    #* torch.Size([6, 1, 5, 5])
                              #* 第一个数表示输出的通道数，即filter的数量
                              #* 第二个数表示输入的通道数，也可以看做是滤波器的深度
                              #* 第三和第四个数表示filter的大小

torch.Size([6, 1, 5, 5])

In [19]:
network.conv1.weight[0].shape

torch.Size([1, 5, 5])

In [20]:
for param in network.parameters():    # 访问参数
    print(param.shape)  

torch.Size([6, 1, 5, 5])
torch.Size([6])
torch.Size([12, 6, 5, 5])
torch.Size([12])
torch.Size([120, 192])
torch.Size([120])
torch.Size([60, 120])
torch.Size([60])
torch.Size([10, 60])
torch.Size([10])


In [21]:
for name, param in network.named_parameters():
    print(name, '\t\t', param.shape)

conv1.weight 		 torch.Size([6, 1, 5, 5])
conv1.bias 		 torch.Size([6])
conv2.weight 		 torch.Size([12, 6, 5, 5])
conv2.bias 		 torch.Size([12])
fc1.weight 		 torch.Size([120, 192])
fc1.bias 		 torch.Size([120])
fc2.weight 		 torch.Size([60, 120])
fc2.bias 		 torch.Size([60])
out.weight 		 torch.Size([10, 60])
out.bias 		 torch.Size([10])


In [22]:
in_features = torch.tensor([1,2,3,4], dtype=torch.float32)

In [23]:
weight_matrix = torch.tensor([
    [1,2,3,4],
    [2,3,4,5],
    [3,4,5,6]
], dtype=torch.float32)

In [24]:
weight_matrix.matmul(in_features)

tensor([30., 40., 50.])

In [25]:
fc = nn.Linear(in_features=4, out_features=3, bias=False)

In [26]:
fc.weight = nn.Parameter(weight_matrix)   # 手动设置线性层的权重

In [27]:
fc(in_features)      # 关闭偏置值，得到整数输出

tensor([30., 40., 50.], grad_fn=<SqueezeBackward3>)