In [1]:
import torch

In [2]:
t = torch.tensor([1, 2, 3])   #*默认在cpu上计算
t

tensor([1, 2, 3])

In [4]:
t = t.cuda()    #* 可以有多个gpu，编号为gpu的序号
t

tensor([1, 2, 3], device='cuda:0')

In [5]:
a = list(range(1,5))
a

[1, 2, 3, 4]

In [8]:
dd = [[i for i in range(1,4)], \
    [i for i in range(4,7)], \
    [i for i in range(7,10)]]

In [9]:
dd

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [11]:
t = torch.tensor(dd)
t

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [12]:
type(t)

torch.Tensor

In [13]:
t.shape

torch.Size([3, 3])

In [15]:
t1 = t.reshape(1,9)

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [16]:
t1 = t.shape

torch.Size([3, 3])

In [1]:
import torch
import numpy as np

In [2]:
t = torch.Tensor()

### **Tensor Attributes**

In [3]:
print(t.device)
print(t.dtype)
print(t.layout)

cpu
torch.float32
torch.strided


In [4]:
t1 = torch.tensor([1,2,3])
t2 = t1.cuda()

In [5]:
# t1 + t2 Error
  

### **Creation options using data**

In [6]:
data = np.array([1,2,3])
type(data)

numpy.ndarray

In [7]:
torch.Tensor(data)

tensor([1., 2., 3.])

In [8]:
torch.tensor(data)

tensor([1, 2, 3], dtype=torch.int32)

In [9]:
torch.as_tensor(data)

tensor([1, 2, 3], dtype=torch.int32)

In [10]:
torch.from_numpy(data)

tensor([1, 2, 3], dtype=torch.int32)

In [11]:
torch.eye(2)

tensor([[1., 0.],
        [0., 1.]])

In [15]:
torch.zeros(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [16]:
torch.ones(2,2)

tensor([[1., 1.],
        [1., 1.]])

In [18]:
torch.rand(2,2)

tensor([[0.4139, 0.8625],
        [0.2772, 0.3047]])

### **Creating PyTorch Tensors - Best Options**

In [ ]:
data = np.array([1,2,3])

In [19]:
t1 = torch.Tensor(data) #* Construtor Function
t2 = torch.tensor(data)  #* Factory Function
t3 = torch.as_tensor(data) #* Factory Function
t4 = torch.from_numpy(data) #* Factory Function

In [20]:
print(t1)
print(t2)
print(t3)
print(t4)

tensor([1., 2., 3.])
tensor([1, 2, 3], dtype=torch.int32)
tensor([1, 2, 3], dtype=torch.int32)
tensor([1, 2, 3], dtype=torch.int32)


In [22]:
print(t1.dtype)
print(t2.dtype)
print(t3.dtype)
print(t4.dtype)

torch.float32
torch.int32
torch.int32
torch.int32


In [23]:
torch.tensor(np.array([1,2,3]))

tensor([1, 2, 3], dtype=torch.int32)

In [24]:
torch.tensor(np.array([1.,2.,3.]))

tensor([1., 2., 3.], dtype=torch.float64)

In [26]:
torch.tensor(np.array([1,2,3]),dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

### **Memory: Sharing and Copying**

In [27]:
data = np.array([1,2,3])
data

array([1, 2, 3])

In [33]:
t1 = torch.Tensor(data)    #* copy
t2 = torch.tensor(data)    #* copy 
t3 = torch.as_tensor(data)  #* share
t4 = torch.from_numpy(data) #* share

In [30]:
data[0] = 0
data[1] = 0
data[2] = 0

In [31]:
print(t1)
print(t2)

tensor([1., 2., 3.])
tensor([1, 2, 3], dtype=torch.int32)


In [32]:
print(t3)
print(t4)

tensor([0, 0, 0], dtype=torch.int32)
tensor([0, 0, 0], dtype=torch.int32)


### **Tensor Operation Types**

In [38]:
# reshape

t = torch.tensor(
    [
    [1,1,1,1],
    [2,2,2,2],
    [3,3,3,3]
    ],dtype=torch.float64
)

In [39]:
t.size()

torch.Size([3, 4])

In [40]:
t.shape

torch.Size([3, 4])

In [41]:
len(t.shape)

2

In [42]:
torch.tensor(t.shape).prod()

tensor(12)

In [44]:
t.numel()

12

In [45]:
t.reshape(1,12)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]], dtype=torch.float64)

In [46]:
t.reshape(2,6)

tensor([[1., 1., 1., 1., 2., 2.],
        [2., 2., 3., 3., 3., 3.]], dtype=torch.float64)

In [47]:
t.reshape(6,2)

tensor([[1., 1.],
        [1., 1.],
        [2., 2.],
        [2., 2.],
        [3., 3.],
        [3., 3.]], dtype=torch.float64)

In [48]:
t.reshape(12,1)

tensor([[1.],
        [1.],
        [1.],
        [1.],
        [2.],
        [2.],
        [2.],
        [2.],
        [3.],
        [3.],
        [3.],
        [3.]], dtype=torch.float64)

In [49]:
t.reshape(2,2,3)

tensor([[[1., 1., 1.],
         [1., 2., 2.]],

        [[2., 2., 3.],
         [3., 3., 3.]]], dtype=torch.float64)

In [50]:
t

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.]], dtype=torch.float64)

In [54]:
print(t.reshape(1,12))
print(t.reshape(1,12).shape)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]], dtype=torch.float64)
torch.Size([1, 12])


In [55]:
print(t.reshape(1,12).squeeze())
print(t.reshape(1,12).squeeze().shape)


tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.], dtype=torch.float64)
torch.Size([12])


In [58]:
print(t.reshape(1,12).squeeze().unsqueeze(dim=0))
print(t.reshape(1,12).squeeze().unsqueeze(dim=0).shape)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]], dtype=torch.float64)
torch.Size([1, 12])


In [60]:
def flatten(t):
    t = t.reshape(1,-1)
    t = t.squeeze()
    return t

In [61]:
flatten(t)

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.], dtype=torch.float64)

### **CNN Flatten Operation Visualized - Tensor Batch Processing for Deep Learning**

In [64]:
t1 = torch.tensor([
    [1,1,1,1],
    [1,1,1,1],
    [1,1,1,1],
    [1,1,1,1]
])

In [65]:
t2 = torch.tensor([
    [2,2,2,2],
    [2,2,2,2],
    [2,2,2,2],
    [2,2,2,2]
])

In [66]:
t3 = torch.tensor([
    [3,3,3,3],
    [3,3,3,3],
    [3,3,3,3],
    [3,3,3,3]
])

In [67]:
t = torch.stack((t1,t2,t3))
t.shape

torch.Size([3, 4, 4])

In [68]:
t

tensor([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[2, 2, 2, 2],
         [2, 2, 2, 2],
         [2, 2, 2, 2],
         [2, 2, 2, 2]],

        [[3, 3, 3, 3],
         [3, 3, 3, 3],
         [3, 3, 3, 3],
         [3, 3, 3, 3]]])

In [70]:
t = t.reshape(3,1,4,4)    #* Add channel
t

tensor([[[[1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1]]],


        [[[2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2]]],


        [[[3, 3, 3, 3],
          [3, 3, 3, 3],
          [3, 3, 3, 3],
          [3, 3, 3, 3]]]])

In [71]:
t[0]  #* first image

tensor([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]]])

In [72]:
t[0][0]    #* first color channel for first image

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])

In [73]:
t[0][0][0]  #* first row of the first color channel of first image

tensor([1, 1, 1, 1])

In [74]:
t[0][0][0][0]

tensor(1)

In [75]:
t.reshape(1,-1)[0]

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [76]:
t.reshape(-1)

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [79]:
t.view(t.numel())  #* torch.view() reshape tensor

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [80]:
t.flatten()

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [82]:
t.flatten(start_dim=1).shape

torch.Size([3, 16])

### **Element-wise tensor operations - Deep Learning and Neural Networks**

In [83]:
t1 = torch.tensor([
    [1,2],
    [3,4]
], dtype=torch.float32)

t2 = torch.tensor([
    [9,8],
    [7,6]
],dtype=torch.float32)

In [84]:
t1[0]

tensor([1., 2.])

In [85]:
t1[0][0]

tensor(1.)

In [86]:
t1[0][0]

tensor(1.)

In [87]:
t2[0][0]

tensor(9.)

In [88]:
t1 + t2

tensor([[10., 10.],
        [10., 10.]])

In [89]:
t1 + 2

tensor([[3., 4.],
        [5., 6.]])

In [90]:
t1 - 2

tensor([[-1.,  0.],
        [ 1.,  2.]])

In [91]:
t1 * 2

tensor([[2., 4.],
        [6., 8.]])

In [92]:
t1 / 2

tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])

In [93]:
t1.add(2)

tensor([[3., 4.],
        [5., 6.]])

In [94]:
t1.sub(2)

tensor([[-1.,  0.],
        [ 1.,  2.]])

In [95]:
t1.mul(2)

tensor([[2., 4.],
        [6., 8.]])

In [96]:
t1.div(2)

tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])

In [97]:
np.broadcast_to(2, t1.shape)

array([[2, 2],
       [2, 2]])

In [98]:
t1 = torch.tensor([
    [1,1],
    [1,1]
],dtype=torch.float32)

t2 = torch.tensor([2,4], dtype=torch.float32)

In [99]:
t1.shape

torch.Size([2, 2])

In [100]:
t2.shape

torch.Size([2])

In [101]:
t2 = t2.numpy()

In [102]:
t2 = np.broadcast_to(t2,t1.shape)

In [103]:
t1 + t2

tensor([[3., 5.],
        [3., 5.]])

In [104]:
t = torch.tensor([
    [0,5,7],
    [6,0,7],
    [0,8,0]
], dtype=torch.float32)

In [105]:
t.eq(0)

tensor([[ True, False, False],
        [False,  True, False],
        [ True, False,  True]])

In [106]:
t.ge(0)

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [107]:
t.gt(0)

tensor([[False,  True,  True],
        [ True, False,  True],
        [False,  True, False]])

In [109]:
t.lt(0)

tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])

In [110]:
t.le(7)

tensor([[ True,  True,  True],
        [ True,  True,  True],
        [ True, False,  True]])

In [112]:
t <= torch.tensor(
    np.broadcast_to(7,t.shape)
    ,dtype=torch.float32
)

tensor([[ True,  True,  True],
        [ True,  True,  True],
        [ True, False,  True]])

In [113]:
t <= torch.tensor([
    [7,7,7],
    [7,7,7],
    [7,7,7]
],dtype=torch.float32)

tensor([[ True,  True,  True],
        [ True,  True,  True],
        [ True, False,  True]])

In [114]:
t.abs()

tensor([[0., 5., 7.],
        [6., 0., 7.],
        [0., 8., 0.]])

In [115]:
t.sqrt()

tensor([[0.0000, 2.2361, 2.6458],
        [2.4495, 0.0000, 2.6458],
        [0.0000, 2.8284, 0.0000]])

In [116]:
t.neg()

tensor([[-0., -5., -7.],
        [-6., -0., -7.],
        [-0., -8., -0.]])

In [117]:
t.neg().abs()

tensor([[0., 5., 7.],
        [6., 0., 7.],
        [0., 8., 0.]])

### **Argmax and Reduction Ops - Tensors for Deep Learning**

In [118]:
t = torch.tensor([
    [0,1,0],
    [2,0,2],
    [0,3,0]
],dtype=torch.float32)

In [119]:
t.sum()

tensor(8.)

In [120]:
t.numel()

9

In [122]:
t.sum().numel()

1

In [124]:
t.sum().numel() < t.sum()

tensor(True)

In [125]:
t.prod()

tensor(0.)

In [126]:
t.mean()

tensor(0.8889)

In [127]:
t.std()

tensor(1.1667)

In [128]:
t = torch.tensor([
    [1,1,1,1],
    [2,2,2,2],
    [3,3,3,3]
],dtype=torch.float32)

In [131]:
t.sum(dim=0)

tensor([6., 6., 6., 6.])

In [132]:
t.sum(dim=1)

tensor([ 4.,  8., 12.])

In [133]:
t.sum(dim=0)

tensor([6., 6., 6., 6.])

In [134]:
t[0]

tensor([1., 1., 1., 1.])

In [135]:
t[1]

tensor([2., 2., 2., 2.])

In [136]:
t[2]

tensor([3., 3., 3., 3.])

In [137]:
t[0] + t[1] + t[2]

tensor([6., 6., 6., 6.])

In [138]:
t[0].sum()

tensor(4.)

In [139]:
t[1].sum()

tensor(8.)

In [140]:
t[2].sum()

tensor(12.)

In [141]:
t.sum(dim=1)

tensor([ 4.,  8., 12.])

In [142]:
t = torch.tensor([
    [1,0,0,2],
    [0,3,3,0],
    [4,0,0,5]
],dtype=torch.float32)

In [143]:
t.max()

tensor(5.)

In [144]:
t.argmax()

tensor(11)

In [145]:
t.flatten()

tensor([1., 0., 0., 2., 0., 3., 3., 0., 4., 0., 0., 5.])

In [146]:
t.max(dim=0)

torch.return_types.max(
values=tensor([4., 3., 3., 5.]),
indices=tensor([2, 1, 1, 2]))

In [147]:
t.max(dim=1)

torch.return_types.max(
values=tensor([2., 3., 5.]),
indices=tensor([3, 1, 3]))

In [148]:
t.max(dim=1)

torch.return_types.max(
values=tensor([2., 3., 5.]),
indices=tensor([3, 1, 3]))

In [149]:
t = torch.tensor([
    [1,2,3],
    [4,5,6],
    [7,8,9]
],dtype=torch.float32)

In [150]:
t.mean()

tensor(5.)

In [151]:
t.mean().item()

5.0

In [152]:
t.mean(dim=0).tolist()

[4.0, 5.0, 6.0]

In [153]:
t.mean(dim=0).numpy()

array([4., 5., 6.], dtype=float32)